/**
 * ========================================
 * CANDLEDATAEXPORTER.JAVA - Data Export
 * ========================================
 * 
 * Enunciado: Exportador de datos de velas en múltiples formatos.
 * Genera archivos CSV, tablas formateadas y estructuras JSON
 * para integración con otros sistemas.
 * 
 * @author jalbraton
 * @date 2023-2024
 * @github github.com/jalbatron
 * ========================================
 */

package Examns;

public class CandleDataExporter {
	
	private String exporterName;
	private CandleCounterIterative counter;
	
	public CandleDataExporter(String exporterName) {
		this.exporterName = exporterName;
		this.counter = new CandleCounterIterative();
	}
	
	private String repeatString(String str, int count) {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < count; i++) {
			sb.append(str);
		}
		return sb.toString();
	}
	
	public String exportToCSV(int years) {
		StringBuilder csv = new StringBuilder();
		
		// Header
		csv.append("Year,Candles,Cumulative,Percentage\n");
		
		// Calculate total for percentage
		long total = counter.count(years);
		long cumulative = 0;
		
		// Data rows
		for (int i = 1; i <= years; i++) {
			long candles = counter.count(i);
			cumulative += candles;
			double percentage = (double) candles / total * 100;
			
			csv.append(String.format("%d,%d,%d,%.2f%%\n", 
			                         i, candles, cumulative, percentage));
		}
		
		return csv.toString();
	}
	
	public String exportToJSON(int years) {
		StringBuilder json = new StringBuilder();
		
		json.append("{\n");
		json.append("  \"exporterName\": \"").append(exporterName).append("\",\n");
		json.append("  \"years\": ").append(years).append(",\n");
		json.append("  \"data\": [\n");
		
		for (int i = 1; i <= years; i++) {
			long candles = counter.count(i);
			
			json.append("    {\n");
			json.append("      \"year\": ").append(i).append(",\n");
			json.append("      \"candles\": ").append(candles).append(",\n");
			json.append("      \"formula\": \"").append(i).append("*(").append(i).append("+1)/2\"\n");
			json.append("    }");
			
			if (i < years) {
				json.append(",");
			}
			json.append("\n");
		}
		
		json.append("  ]\n");
		json.append("}\n");
		
		return json.toString();
	}
	
	public String exportToXML(int years) {
		StringBuilder xml = new StringBuilder();
		
		xml.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
		xml.append("<CandleData>\n");
		xml.append("  <Exporter>").append(exporterName).append("</Exporter>\n");
		xml.append("  <Years>").append(years).append("</Years>\n");
		xml.append("  <Records>\n");
		
		for (int i = 1; i <= years; i++) {
			long candles = counter.count(i);
			
			xml.append("    <Record>\n");
			xml.append("      <Year>").append(i).append("</Year>\n");
			xml.append("      <Candles>").append(candles).append("</Candles>\n");
			xml.append("    </Record>\n");
		}
		
		xml.append("  </Records>\n");
		xml.append("</CandleData>\n");
		
		return xml.toString();
	}
	
	public String exportToMarkdownTable(int years) {
		StringBuilder md = new StringBuilder();
		
		md.append("# Candle Consumption Report\n\n");
		md.append("**Generated by:** ").append(exporterName).append("\n\n");
		md.append("| Year | Candles | Cumulative | Growth Rate |\n");
		md.append("|------|---------|------------|-------------|\n");
		
		long cumulative = 0;
		long previousCandles = 0;
		
		for (int i = 1; i <= years; i++) {
			long candles = counter.count(i);
			cumulative += candles;
			double growthRate = previousCandles == 0 ? 0.0 : 
			                    ((double)(candles - previousCandles) / previousCandles * 100);
			
			md.append(String.format("| %4d | %,7d | %,10d | %6.2f%% |\n", 
			                        i, candles, cumulative, growthRate));
			
			previousCandles = candles;
		}
		
		md.append("\n## Summary\n\n");
		md.append("- Total years analyzed: ").append(years).append("\n");
		md.append("- Total candles: ").append(String.format("%,d", cumulative)).append("\n");
		md.append("- Average per year: ").append(String.format("%.2f", (double)cumulative/years)).append("\n");
		
		return md.toString();
	}
	
	public String exportToSQL(int years, String tableName) {
		StringBuilder sql = new StringBuilder();
		
		sql.append("-- SQL Insert Statements for Candle Data\n");
		sql.append("-- Generated by: ").append(exporterName).append("\n\n");
		
		sql.append("CREATE TABLE IF NOT EXISTS ").append(tableName).append(" (\n");
		sql.append("  id INT PRIMARY KEY AUTO_INCREMENT,\n");
		sql.append("  year INT NOT NULL,\n");
		sql.append("  candles BIGINT NOT NULL,\n");
		sql.append("  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n");
		sql.append(");\n\n");
		
		for (int i = 1; i <= years; i++) {
			long candles = counter.count(i);
			sql.append(String.format("INSERT INTO %s (year, candles) VALUES (%d, %d);\n", 
			                         tableName, i, candles));
		}
		
		return sql.toString();
	}
	
	public void printExportSample(String format, int years) {
		System.out.println("========== EXPORT SAMPLE: " + format.toUpperCase() + " ==========");
		System.out.println();
		
		String data;
		switch (format.toLowerCase()) {
			case "csv":
				data = exportToCSV(years);
				break;
			case "json":
				data = exportToJSON(years);
				break;
			case "xml":
				data = exportToXML(years);
				break;
			case "markdown":
				data = exportToMarkdownTable(years);
				break;
			case "sql":
				data = exportToSQL(years, "candle_data");
				break;
			default:
				data = "Unknown format: " + format;
		}
		
		System.out.println(data);
		System.out.println(repeatString("=", 60));
	}
	
	public void exportAllFormats(int years) {
		System.out.println("╔════════════════════════════════════════════════╗");
		System.out.println("║       MULTI-FORMAT EXPORT DEMO                 ║");
		System.out.println("╚════════════════════════════════════════════════╝\n");
		
		String[] formats = {"CSV", "JSON", "XML", "Markdown", "SQL"};
		
		for (String format : formats) {
			printExportSample(format, years);
			System.out.println("\n");
		}
	}
	
	public void generateFileExportScript(int years) {
		System.out.println("===== FILE EXPORT SCRIPT GENERATOR =====");
		System.out.println("// PowerShell script to export data to files");
		System.out.println();
		System.out.println("$data_csv = @\"");
		System.out.println(exportToCSV(years));
		System.out.println("\"@");
		System.out.println("$data_csv | Out-File -FilePath 'candle_data.csv' -Encoding UTF8");
		System.out.println();
		System.out.println("$data_json = @\"");
		System.out.println(exportToJSON(years));
		System.out.println("\"@");
		System.out.println("$data_json | Out-File -FilePath 'candle_data.json' -Encoding UTF8");
		System.out.println();
		System.out.println("Write-Host 'Export completed successfully!'");
		System.out.println("========================================");
	}
	
	public static void main(String[] args) {
		CandleDataExporter exporter = new CandleDataExporter("Production Exporter v1.0");
		
		// Export samples
		System.out.println("CSV FORMAT:");
		exporter.printExportSample("CSV", 5);
		System.out.println("\n");
		
		System.out.println("JSON FORMAT:");
		exporter.printExportSample("JSON", 5);
		System.out.println("\n");
		
		System.out.println("MARKDOWN FORMAT:");
		exporter.printExportSample("Markdown", 5);
		System.out.println("\n");
		
		// Generate export script
		exporter.generateFileExportScript(5);
		
		System.out.println("\n\n");
		
		// Full export demo
		CandleDataExporter demoExporter = new CandleDataExporter("Demo Exporter");
		demoExporter.exportAllFormats(3);
	}
}
