/**
 * ========================================
 * CANDLEREPORTGENERATOR.JAVA - Report Generation
 * ========================================
 * 
 * Enunciado: Generador de reportes completos sobre consumo de
 * velas. Crea informes detallados con estadísticas, tendencias
 * y recomendaciones para la toma de decisiones.
 * 
 * @author jalbraton
 * @date 2023-2024
 * @github github.com/jalbatron
 * ========================================
 */

package Examns;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class CandleReportGenerator {
	
	private String reportTitle;
	private CandleCounterIterative counter;
	private String generatedBy;
	
	public CandleReportGenerator(String reportTitle, String generatedBy) {
		this.reportTitle = reportTitle;
		this.generatedBy = generatedBy;
		this.counter = new CandleCounterIterative();
	}
	
	private String repeatString(String str, int count) {
		StringBuilder sb = new StringBuilder();
		for (int i = 0; i < count; i++) {
			sb.append(str);
		}
		return sb.toString();
	}
	
	public void generateExecutiveSummary(int years) {
		System.out.println("╔════════════════════════════════════════════════╗");
		System.out.println("║         EXECUTIVE SUMMARY REPORT               ║");
		System.out.println("╚════════════════════════════════════════════════╝");
		System.out.println();
		
		printReportHeader();
		
		long totalCandles = counter.count(years);
		double avgPerYear = (double) totalCandles / years;
		long lastYearConsumption = years;
		
		System.out.println("KEY METRICS:");
		System.out.println(repeatString("─", 50));
		System.out.printf("  Analysis Period:        %d years\n", years);
		System.out.printf("  Total Consumption:      %,d candles\n", totalCandles);
		System.out.printf("  Average per Year:       %.2f candles\n", avgPerYear);
		System.out.printf("  Latest Year Usage:      %,d candles\n", lastYearConsumption);
		System.out.printf("  Growth Rate:            %.2f%%\n", 
		                  calculateGrowthRate(years));
		System.out.println();
		
		printTrendAnalysis(years);
		printRecommendations(years);
		
		System.out.println();
		System.out.println(repeatString("═", 50));
		System.out.println("End of Executive Summary");
		System.out.println(repeatString("═", 50));
	}
	
	public void generateDetailedReport(int years) {
		System.out.println("╔════════════════════════════════════════════════╗");
		System.out.println("║           DETAILED ANALYSIS REPORT             ║");
		System.out.println("╚════════════════════════════════════════════════╝");
		System.out.println();
		
		printReportHeader();
		
		System.out.println("YEAR-BY-YEAR BREAKDOWN:");
		System.out.println(repeatString("─", 50));
		System.out.println("┌──────┬──────────────┬──────────────┬──────────┐");
		System.out.println("│ Year │   Candles    │  Cumulative  │  Growth  │");
		System.out.println("├──────┼──────────────┼──────────────┼──────────┤");
		
		long cumulative = 0;
		long previousCandles = 0;
		
		for (int i = 1; i <= years; i++) {
			long candles = counter.count(i);
			cumulative += candles;
			double growth = previousCandles == 0 ? 0 : 
			                ((double)(candles - previousCandles) / previousCandles * 100);
			
			System.out.printf("│ %4d │ %,10d   │ %,10d   │ %6.2f%% │\n", 
			                  i, candles, cumulative, growth);
			
			previousCandles = candles;
		}
		
		System.out.println("└──────┴──────────────┴──────────────┴──────────┘");
		System.out.println();
		
		printQuarterlyBreakdown(years);
		printCostAnalysis(years, 2.50); // $2.50 per candle
		
		System.out.println();
		System.out.println(repeatString("═", 50));
		System.out.println("End of Detailed Report");
		System.out.println(repeatString("═", 50));
	}
	
	private void printReportHeader() {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
		String timestamp = LocalDateTime.now().format(formatter);
		
		System.out.println("Report Title:    " + reportTitle);
		System.out.println("Generated By:    " + generatedBy);
		System.out.println("Generated On:    " + timestamp);
		System.out.println("Report Type:     Candle Consumption Analysis");
		System.out.println();
		System.out.println(repeatString("═", 50));
		System.out.println();
	}
	
	private double calculateGrowthRate(int years) {
		if (years <= 1) return 0.0;
		
		long firstYear = 1;
		long lastYear = counter.count(years);
		
		return ((double)(lastYear - firstYear) / firstYear) * 100;
	}
	
	private void printTrendAnalysis(int years) {
		System.out.println("TREND ANALYSIS:");
		System.out.println(repeatString("─", 50));
		
		long[] recentYears = new long[Math.min(5, years)];
		for (int i = 0; i < recentYears.length; i++) {
			recentYears[i] = counter.count(years - recentYears.length + i + 1);
		}
		
		boolean increasing = true;
		for (int i = 1; i < recentYears.length; i++) {
			if (recentYears[i] <= recentYears[i - 1]) {
				increasing = false;
				break;
			}
		}
		
		System.out.println("  Trend Direction:     " + (increasing ? "↑ INCREASING" : "→ STABLE"));
		System.out.println("  Pattern:             LINEAR GROWTH");
		System.out.println("  Predictability:      HIGH");
		System.out.println("  Volatility:          LOW");
	}
	
	private void printRecommendations(int years) {
		System.out.println();
		System.out.println("RECOMMENDATIONS:");
		System.out.println(repeatString("─", 50));
		
		long nextYearPrediction = counter.count(years + 1);
		long bufferStock = (long) (nextYearPrediction * 0.20); // 20% buffer
		
		System.out.println("  1. Order Forecast:");
		System.out.printf("     Next year needs: %,d candles\n", nextYearPrediction);
		System.out.printf("     Recommended buffer: %,d candles (20%%)\n", bufferStock);
		System.out.printf("     Total order: %,d candles\n", nextYearPrediction + bufferStock);
		System.out.println();
		
		System.out.println("  2. Inventory Management:");
		System.out.println("     ✓ Implement quarterly ordering");
		System.out.println("     ✓ Maintain 20% safety stock");
		System.out.println("     ✓ Monitor consumption patterns monthly");
		System.out.println();
		
		System.out.println("  3. Cost Optimization:");
		System.out.println("     ✓ Consider bulk ordering discounts");
		System.out.println("     ✓ Negotiate long-term supplier contracts");
		System.out.println("     ✓ Explore alternative suppliers");
	}
	
	private void printQuarterlyBreakdown(int years) {
		System.out.println("QUARTERLY BREAKDOWN (Last 4 quarters):");
		System.out.println(repeatString("─", 50));
		
		int quartersToShow = Math.min(4, years);
		for (int q = 0; q < quartersToShow; q++) {
			int year = years - quartersToShow + q + 1;
			long candles = counter.count(year);
			
			System.out.printf("  Q%d (Year %d): %,10d candles\n", q + 1, year, candles);
		}
		System.out.println();
	}
	
	private void printCostAnalysis(int years, double costPerCandle) {
		System.out.println("COST ANALYSIS:");
		System.out.println(repeatString("─", 50));
		
		long totalCandles = counter.count(years);
		double totalCost = totalCandles * costPerCandle;
		double avgCostPerYear = totalCost / years;
		
		System.out.printf("  Cost per Candle:     $%.2f\n", costPerCandle);
		System.out.printf("  Total Candles:       %,d\n", totalCandles);
		System.out.printf("  Total Cost:          $%,.2f\n", totalCost);
		System.out.printf("  Average Cost/Year:   $%,.2f\n", avgCostPerYear);
		System.out.println();
		
		// Cost projections
		long nextYearCandles = counter.count(years + 1);
		double nextYearCost = nextYearCandles * costPerCandle;
		
		System.out.println("  Next Year Projection:");
		System.out.printf("    Expected candles:  %,d\n", nextYearCandles);
		System.out.printf("    Expected cost:     $%,.2f\n", nextYearCost);
	}
	
	public static void main(String[] args) {
		CandleReportGenerator reporter = new CandleReportGenerator(
			"Annual Candle Consumption Report 2024",
			"Operations Department"
		);
		
		// Generate executive summary
		reporter.generateExecutiveSummary(10);
		
		System.out.println("\n\n");
		
		// Generate detailed report
		reporter.generateDetailedReport(15);
		
		System.out.println("\n\n");
		
		// Custom report
		CandleReportGenerator customReport = new CandleReportGenerator(
			"5-Year Strategic Planning Report",
			"Strategic Planning Team"
		);
		customReport.generateExecutiveSummary(5);
	}
}
